[2025-03-23T06:45:43.704+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T06:45:43.857+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.create_aqi_table scheduled__2025-03-22T00:00:00+00:00 [queued]>
[2025-03-23T06:45:43.947+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.create_aqi_table scheduled__2025-03-22T00:00:00+00:00 [queued]>
[2025-03-23T06:45:43.947+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-23T06:45:44.080+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_aqi_table> on 2025-03-22 00:00:00+00:00
[2025-03-23T06:45:44.207+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'create_aqi_table', 'scheduled__2025-03-22T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpm1ibfbnu']
[2025-03-23T06:45:44.225+0000] {standard_task_runner.py:105} INFO - Job 90: Subtask create_aqi_table
[2025-03-23T06:45:44.222+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=225) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-23T06:45:44.235+0000] {standard_task_runner.py:72} INFO - Started process 309 to run task
[2025-03-23T06:45:44.724+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.create_aqi_table scheduled__2025-03-22T00:00:00+00:00 [running]> on host 786551ffa427
[2025-03-23T06:45:45.577+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='create_aqi_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-22T00:00:00+00:00'
[2025-03-23T06:45:45.586+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-23T06:45:45.586+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-23T06:45:45.587+0000] {logging_mixin.py:190} INFO - Current task name:create_aqi_table state:running start_date:2025-03-23 06:45:43.881136+00:00
[2025-03-23T06:45:45.587+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-23T06:45:45.589+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T06:45:45.633+0000] {base.py:84} INFO - Retrieving connection '***_default'
[2025-03-23T06:45:45.682+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 58, in _create_aqi_table
    connection = pg_hook.get_conn()
                 ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 189, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: FATAL:  database "aqi_project" does not exist

[2025-03-23T06:45:45.745+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-23T06:45:45.752+0000] {logging_mixin.py:190} INFO - Task start:2025-03-23 06:45:43.881136+00:00 end:2025-03-23 06:45:45.744874+00:00 duration:1.863738
[2025-03-23T06:45:45.752+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_aqi_table> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-22 00:00:00+00:00: scheduled__2025-03-22T00:00:00+00:00, state:running, queued_at: 2025-03-23 06:45:26.384021+00:00. externally triggered: False>
[2025-03-23T06:45:45.753+0000] {logging_mixin.py:190} INFO - Failure caused by connection to server at "db" (172.18.0.2), port 5432 failed: FATAL:  database "aqi_project" does not exist
[2025-03-23T06:45:45.753+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aqi_etl_pipeline, task_id=create_aqi_table, run_id=scheduled__2025-03-22T00:00:00+00:00, execution_date=20250322T000000, start_date=20250323T064543, end_date=20250323T064545
[2025-03-23T06:45:46.013+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T06:45:46.028+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 90 for task create_aqi_table (connection to server at "db" (172.18.0.2), port 5432 failed: FATAL:  database "aqi_project" does not exist
; 309)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 58, in _create_aqi_table
    connection = pg_hook.get_conn()
                 ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 189, in get_conn
    self.conn = psycopg2.connect(**conn_args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
psycopg2.OperationalError: connection to server at "db" (172.18.0.2), port 5432 failed: FATAL:  database "aqi_project" does not exist

[2025-03-23T06:45:46.181+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-23T06:45:46.329+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-23T08:14:12.205+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T08:14:12.312+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.create_aqi_table scheduled__2025-03-22T00:00:00+00:00 [queued]>
[2025-03-23T08:14:12.376+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.create_aqi_table scheduled__2025-03-22T00:00:00+00:00 [queued]>
[2025-03-23T08:14:12.377+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-23T08:14:12.479+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_aqi_table> on 2025-03-22 00:00:00+00:00
[2025-03-23T08:14:12.575+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=30165) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-23T08:14:12.581+0000] {standard_task_runner.py:72} INFO - Started process 30253 to run task
[2025-03-23T08:14:12.576+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'create_aqi_table', 'scheduled__2025-03-22T00:00:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpihzjoath']
[2025-03-23T08:14:12.586+0000] {standard_task_runner.py:105} INFO - Job 255: Subtask create_aqi_table
[2025-03-23T08:14:12.781+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.create_aqi_table scheduled__2025-03-22T00:00:00+00:00 [running]> on host ed55a332e3f9
[2025-03-23T08:14:13.134+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='create_aqi_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-22T00:00:00+00:00'
[2025-03-23T08:14:13.135+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-23T08:14:13.140+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-23T08:14:13.141+0000] {logging_mixin.py:190} INFO - Current task name:create_aqi_table state:running start_date:2025-03-23 08:14:12.324148+00:00
[2025-03-23T08:14:13.143+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-23T08:14:13.143+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T08:14:13.174+0000] {base.py:84} INFO - Retrieving connection '***_default'
[2025-03-23T08:14:13.211+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T08:14:13.230+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T08:14:13.233+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=aqi_etl_pipeline, task_id=create_aqi_table, run_id=scheduled__2025-03-22T00:00:00+00:00, execution_date=20250322T000000, start_date=20250323T081412, end_date=20250323T081413
[2025-03-23T08:14:13.259+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-23T08:14:13.259+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-23T08:14:13.259+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline queued_at:2025-03-23 08:13:40.148455+00:00
[2025-03-23T08:14:13.260+0000] {logging_mixin.py:190} INFO - Task hostname:ed55a332e3f9 operator:PythonOperator
[2025-03-23T08:14:13.305+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T08:14:13.371+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T08:14:13.379+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
