[2025-03-23T06:45:53.744+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T06:45:53.851+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-23T06:45:54.010+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-23T06:45:54.026+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-23T06:45:54.175+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validate_aqi_data> on 2025-03-21 00:00:00+00:00
[2025-03-23T06:45:54.327+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'validate_aqi_data', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '97', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmp_7zhqgff']
[2025-03-23T06:45:54.331+0000] {standard_task_runner.py:105} INFO - Job 97: Subtask validate_aqi_data
[2025-03-23T06:45:54.411+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=350) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-23T06:45:54.427+0000] {standard_task_runner.py:72} INFO - Started process 408 to run task
[2025-03-23T06:45:54.951+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-21T00:00:00+00:00 [running]> on host 786551ffa427
[2025-03-23T06:45:55.348+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_aqi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-23T06:45:55.349+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-23T06:45:55.349+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-23T06:45:55.362+0000] {logging_mixin.py:190} INFO - Current task name:validate_aqi_data state:running start_date:2025-03-23 06:45:53.864343+00:00
[2025-03-23T06:45:55.362+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-23T06:45:55.362+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T06:45:55.365+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T06:45:55.424+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T06:45:55.424+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=aqi_etl_pipeline, task_id=validate_aqi_data, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250323T064553, end_date=20250323T064555
[2025-03-23T06:45:55.481+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-23T06:45:55.481+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-23T06:45:55.482+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline queued_at:2025-03-23 06:45:26.135029+00:00
[2025-03-23T06:45:55.482+0000] {logging_mixin.py:190} INFO - Task hostname:786551ffa427 operator:PythonOperator
[2025-03-23T06:45:55.581+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T06:45:55.698+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T06:45:55.704+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-23T08:14:13.001+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T08:14:13.095+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-23T08:14:13.126+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-21T00:00:00+00:00 [queued]>
[2025-03-23T08:14:13.128+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-23T08:14:13.215+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validate_aqi_data> on 2025-03-21 00:00:00+00:00
[2025-03-23T08:14:13.253+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=30166) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-23T08:14:13.256+0000] {standard_task_runner.py:72} INFO - Started process 30267 to run task
[2025-03-23T08:14:13.262+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'validate_aqi_data', 'scheduled__2025-03-21T00:00:00+00:00', '--job-id', '257', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmp7u5vpper']
[2025-03-23T08:14:13.267+0000] {standard_task_runner.py:105} INFO - Job 257: Subtask validate_aqi_data
[2025-03-23T08:14:13.432+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-21T00:00:00+00:00 [running]> on host ed55a332e3f9
[2025-03-23T08:14:13.677+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_aqi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T00:00:00+00:00'
[2025-03-23T08:14:13.678+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-23T08:14:13.678+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-23T08:14:13.678+0000] {logging_mixin.py:190} INFO - Current task name:validate_aqi_data state:running start_date:2025-03-23 08:14:13.096244+00:00
[2025-03-23T08:14:13.679+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-23T08:14:13.683+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T08:14:13.684+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 48, in _validate_aqi_data
    assert "data" in data and "current" in data["data"], "Invalid data format"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid data format
[2025-03-23T08:14:13.699+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-23T08:14:13.700+0000] {logging_mixin.py:190} INFO - Task start:2025-03-23 08:14:13.096244+00:00 end:2025-03-23 08:14:13.699413+00:00 duration:0.603169
[2025-03-23T08:14:13.700+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): validate_aqi_data> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-21 00:00:00+00:00: scheduled__2025-03-21T00:00:00+00:00, state:running, queued_at: 2025-03-23 08:13:38.446162+00:00. externally triggered: False>
[2025-03-23T08:14:13.700+0000] {logging_mixin.py:190} INFO - Failure caused by Invalid data format
[2025-03-23T08:14:13.701+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aqi_etl_pipeline, task_id=validate_aqi_data, run_id=scheduled__2025-03-21T00:00:00+00:00, execution_date=20250321T000000, start_date=20250323T081413, end_date=20250323T081413
[2025-03-23T08:14:13.720+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T08:14:13.724+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 257 for task validate_aqi_data (Invalid data format; 30267)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 48, in _validate_aqi_data
    assert "data" in data and "current" in data["data"], "Invalid data format"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid data format
[2025-03-23T08:14:13.767+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-23T08:14:13.844+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T08:14:13.857+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
