[2025-03-23T06:45:55.066+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T06:45:55.173+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-23T06:45:55.204+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-23T06:45:55.204+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-23T06:45:55.282+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validate_aqi_data> on 2025-03-20 00:00:00+00:00
[2025-03-23T06:45:55.354+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'validate_aqi_data', 'scheduled__2025-03-20T00:00:00+00:00', '--job-id', '98', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpe5b1iwp7']
[2025-03-23T06:45:55.367+0000] {standard_task_runner.py:105} INFO - Job 98: Subtask validate_aqi_data
[2025-03-23T06:45:55.372+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=340) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-23T06:45:55.379+0000] {standard_task_runner.py:72} INFO - Started process 412 to run task
[2025-03-23T06:45:55.572+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-20T00:00:00+00:00 [running]> on host 786551ffa427
[2025-03-23T06:45:55.856+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_aqi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T00:00:00+00:00'
[2025-03-23T06:45:55.867+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-23T06:45:55.869+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-23T06:45:55.870+0000] {logging_mixin.py:190} INFO - Current task name:validate_aqi_data state:running start_date:2025-03-23 06:45:55.176416+00:00
[2025-03-23T06:45:55.870+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-23T06:45:55.871+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T06:45:55.872+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-23T06:45:55.907+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T06:45:55.907+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=aqi_etl_pipeline, task_id=validate_aqi_data, run_id=scheduled__2025-03-20T00:00:00+00:00, execution_date=20250320T000000, start_date=20250323T064555, end_date=20250323T064555
[2025-03-23T06:45:55.947+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-23T06:45:55.947+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-23T06:45:55.948+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline queued_at:2025-03-23 06:45:24.803509+00:00
[2025-03-23T06:45:55.949+0000] {logging_mixin.py:190} INFO - Task hostname:786551ffa427 operator:PythonOperator
[2025-03-23T06:45:56.033+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-23T06:45:56.091+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T06:45:56.096+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-23T08:14:11.718+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-23T08:14:11.768+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-23T08:14:11.785+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-20T00:00:00+00:00 [queued]>
[2025-03-23T08:14:11.785+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-23T08:14:11.815+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): validate_aqi_data> on 2025-03-20 00:00:00+00:00
[2025-03-23T08:14:11.860+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=30157) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-23T08:14:11.866+0000] {standard_task_runner.py:72} INFO - Started process 30245 to run task
[2025-03-23T08:14:11.862+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'validate_aqi_data', 'scheduled__2025-03-20T00:00:00+00:00', '--job-id', '254', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmp9bslw3nt']
[2025-03-23T08:14:11.868+0000] {standard_task_runner.py:105} INFO - Job 254: Subtask validate_aqi_data
[2025-03-23T08:14:12.082+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.validate_aqi_data scheduled__2025-03-20T00:00:00+00:00 [running]> on host ed55a332e3f9
[2025-03-23T08:14:12.533+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='validate_aqi_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-20T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-20T00:00:00+00:00'
[2025-03-23T08:14:12.539+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-23T08:14:12.542+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-23T08:14:12.543+0000] {logging_mixin.py:190} INFO - Current task name:validate_aqi_data state:running start_date:2025-03-23 08:14:11.769386+00:00
[2025-03-23T08:14:12.543+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-23T08:14:12.543+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-23T08:14:12.549+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 48, in _validate_aqi_data
    assert "data" in data and "current" in data["data"], "Invalid data format"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid data format
[2025-03-23T08:14:12.580+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-23T08:14:12.584+0000] {logging_mixin.py:190} INFO - Task start:2025-03-23 08:14:11.769386+00:00 end:2025-03-23 08:14:12.579577+00:00 duration:0.810191
[2025-03-23T08:14:12.587+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): validate_aqi_data> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-20 00:00:00+00:00: scheduled__2025-03-20T00:00:00+00:00, state:running, queued_at: 2025-03-23 08:13:36.176997+00:00. externally triggered: False>
[2025-03-23T08:14:12.587+0000] {logging_mixin.py:190} INFO - Failure caused by Invalid data format
[2025-03-23T08:14:12.588+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aqi_etl_pipeline, task_id=validate_aqi_data, run_id=scheduled__2025-03-20T00:00:00+00:00, execution_date=20250320T000000, start_date=20250323T081411, end_date=20250323T081412
[2025-03-23T08:14:12.643+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-23T08:14:12.644+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 254 for task validate_aqi_data (Invalid data format; 30245)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 48, in _validate_aqi_data
    assert "data" in data and "current" in data["data"], "Invalid data format"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: Invalid data format
[2025-03-23T08:14:12.741+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-23T08:14:12.852+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-23T08:14:12.873+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
