[2025-03-19T17:31:50.421+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-19T17:31:50.442+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.create_aqi_table manual__2025-03-19T17:31:47.369439+00:00 [queued]>
[2025-03-19T17:31:50.450+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.create_aqi_table manual__2025-03-19T17:31:47.369439+00:00 [queued]>
[2025-03-19T17:31:50.451+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-19T17:31:50.467+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): create_aqi_table> on 2025-03-19 17:31:47.369439+00:00
[2025-03-19T17:31:50.488+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'create_aqi_table', 'manual__2025-03-19T17:31:47.369439+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmprdcoijh4']
[2025-03-19T17:31:50.494+0000] {standard_task_runner.py:105} INFO - Job 9: Subtask create_aqi_table
[2025-03-19T17:31:50.494+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=3131) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-19T17:31:50.495+0000] {standard_task_runner.py:72} INFO - Started process 3138 to run task
[2025-03-19T17:31:50.551+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.create_aqi_table manual__2025-03-19T17:31:47.369439+00:00 [running]> on host c9f5ebbb7823
[2025-03-19T17:31:50.653+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='create_aqi_table' AIRFLOW_CTX_EXECUTION_DATE='2025-03-19T17:31:47.369439+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-19T17:31:47.369439+00:00'
[2025-03-19T17:31:50.655+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-19T17:31:50.655+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-19T17:31:50.656+0000] {logging_mixin.py:190} INFO - Current task name:create_aqi_table state:running start_date:2025-03-19 17:31:50.443062+00:00
[2025-03-19T17:31:50.656+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-19T17:31:50.656+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-19T17:31:50.669+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 55, in _create_aqi_table
    connection = pg_hook.get_conn()
                 ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 157, in get_conn
    conn = deepcopy(self.connection)
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 212, in connection
    self._connection = self.get_connection(self.get_conn_id())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-03-19T17:31:50.683+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-19T17:31:50.683+0000] {logging_mixin.py:190} INFO - Task start:2025-03-19 17:31:50.443062+00:00 end:2025-03-19 17:31:50.683041+00:00 duration:0.239979
[2025-03-19T17:31:50.684+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): create_aqi_table> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-19 17:31:47.369439+00:00: manual__2025-03-19T17:31:47.369439+00:00, state:running, queued_at: 2025-03-19 17:31:47.382810+00:00. externally triggered: True>
[2025-03-19T17:31:50.684+0000] {logging_mixin.py:190} INFO - Failure caused by The conn_id `postgres_default` isn't defined
[2025-03-19T17:31:50.684+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aqi_etl_pipeline, task_id=create_aqi_table, run_id=manual__2025-03-19T17:31:47.369439+00:00, execution_date=20250319T173147, start_date=20250319T173150, end_date=20250319T173150
[2025-03-19T17:31:50.703+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-19T17:31:50.703+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 9 for task create_aqi_table (The conn_id `postgres_default` isn't defined; 3138)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 55, in _create_aqi_table
    connection = pg_hook.get_conn()
                 ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/postgres/hooks/postgres.py", line 157, in get_conn
    conn = deepcopy(self.connection)
                    ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 212, in connection
    self._connection = self.get_connection(self.get_conn_id())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/hooks/base.py", line 83, in get_connection
    conn = Connection.get_connection_from_secrets(conn_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/connection.py", line 537, in get_connection_from_secrets
    raise AirflowNotFoundException(f"The conn_id `{conn_id}` isn't defined")
airflow.exceptions.AirflowNotFoundException: The conn_id `postgres_default` isn't defined
[2025-03-19T17:31:50.754+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-19T17:31:50.787+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-19T17:31:50.791+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
