[2025-03-31T06:26:04.461+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T06:26:04.501+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Nonthaburi manual__2025-03-31T06:16:27.803306+00:00 [queued]>
[2025-03-31T06:26:04.511+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Nonthaburi manual__2025-03-31T06:16:27.803306+00:00 [queued]>
[2025-03-31T06:26:04.512+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2025-03-31T06:26:04.550+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): aqi_tasks_group.get_aqi_data_Nonthaburi> on 2025-03-31 06:16:27.803306+00:00
[2025-03-31T06:26:04.585+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'aqi_tasks_group.get_aqi_data_Nonthaburi', 'manual__2025-03-31T06:16:27.803306+00:00', '--job-id', '858', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpx22pbapk']
[2025-03-31T06:26:04.594+0000] {standard_task_runner.py:105} INFO - Job 858: Subtask aqi_tasks_group.get_aqi_data_Nonthaburi
[2025-03-31T06:26:04.598+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=243) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T06:26:04.604+0000] {standard_task_runner.py:72} INFO - Started process 324 to run task
[2025-03-31T06:26:04.705+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Nonthaburi manual__2025-03-31T06:16:27.803306+00:00 [running]> on host daf74ef548f3
[2025-03-31T06:26:05.027+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='aqi_tasks_group.get_aqi_data_Nonthaburi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T06:16:27.803306+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T06:16:27.803306+00:00'
[2025-03-31T06:26:05.028+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T06:26:05.029+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T06:26:05.030+0000] {logging_mixin.py:190} INFO - Current task name:aqi_tasks_group.get_aqi_data_Nonthaburi state:running start_date:2025-03-31 06:26:04.501946+00:00
[2025-03-31T06:26:05.030+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-31T06:26:05.031+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T06:26:05.034+0000] {api_etl_pipeline.py:28} INFO - Fetching AQI data with params: {'city': 'Nonthaburi', 'state': 'Nonthaburi', 'country': 'Thailand', 'key': '***'}
[2025-03-31T06:26:05.538+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 41, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {data.get('data', {}).get('message', 'Unknown error')}")
ValueError: API Error 400: city_not_found
[2025-03-31T06:26:05.573+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-31T06:26:05.573+0000] {logging_mixin.py:190} INFO - Task start:2025-03-31 06:26:04.501946+00:00 end:2025-03-31 06:26:05.572614+00:00 duration:1.070668
[2025-03-31T06:26:05.575+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): aqi_tasks_group.get_aqi_data_Nonthaburi> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-31 06:16:27.803306+00:00: manual__2025-03-31T06:16:27.803306+00:00, state:running, queued_at: 2025-03-31 06:16:27.819454+00:00. externally triggered: True>
[2025-03-31T06:26:05.576+0000] {logging_mixin.py:190} INFO - Failure caused by API Error 400: city_not_found
[2025-03-31T06:26:05.576+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aqi_etl_pipeline, task_id=aqi_tasks_group.get_aqi_data_Nonthaburi, run_id=manual__2025-03-31T06:16:27.803306+00:00, execution_date=20250331T061627, start_date=20250331T062604, end_date=20250331T062605
[2025-03-31T06:26:05.648+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T06:26:05.649+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 858 for task aqi_tasks_group.get_aqi_data_Nonthaburi (API Error 400: city_not_found; 324)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 41, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {data.get('data', {}).get('message', 'Unknown error')}")
ValueError: API Error 400: city_not_found
[2025-03-31T06:26:05.770+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-31T06:26:05.838+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T06:26:05.858+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
