[2025-03-30T12:31:22.547+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T12:31:22.620+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.get_aqi_data_Nonthaburi manual__2025-03-30T12:20:58.350966+00:00 [queued]>
[2025-03-30T12:31:22.634+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.get_aqi_data_Nonthaburi manual__2025-03-30T12:20:58.350966+00:00 [queued]>
[2025-03-30T12:31:22.635+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-03-30T12:31:22.658+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_aqi_data_Nonthaburi> on 2025-03-30 12:20:58.350966+00:00
[2025-03-30T12:31:22.717+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'get_aqi_data_Nonthaburi', 'manual__2025-03-30T12:20:58.350966+00:00', '--job-id', '611', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpcl9gcpxt']
[2025-03-30T12:31:22.723+0000] {standard_task_runner.py:105} INFO - Job 611: Subtask get_aqi_data_Nonthaburi
[2025-03-30T12:31:22.738+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=31451) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T12:31:22.739+0000] {standard_task_runner.py:72} INFO - Started process 31509 to run task
[2025-03-30T12:31:22.803+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.get_aqi_data_Nonthaburi manual__2025-03-30T12:20:58.350966+00:00 [running]> on host 58b9640d9ecf
[2025-03-30T12:31:23.092+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='get_aqi_data_Nonthaburi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T12:20:58.350966+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T12:20:58.350966+00:00'
[2025-03-30T12:31:23.094+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T12:31:23.095+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T12:31:23.095+0000] {logging_mixin.py:190} INFO - Current task name:get_aqi_data_Nonthaburi state:running start_date:2025-03-30 12:31:22.620557+00:00
[2025-03-30T12:31:23.096+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-30T12:31:23.096+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T12:31:23.468+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 48, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-30T12:31:23.491+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-30T12:31:23.491+0000] {logging_mixin.py:190} INFO - Task start:2025-03-30 12:31:22.620557+00:00 end:2025-03-30 12:31:23.490841+00:00 duration:0.870284
[2025-03-30T12:31:23.492+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_aqi_data_Nonthaburi> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-30 12:20:58.350966+00:00: manual__2025-03-30T12:20:58.350966+00:00, state:running, queued_at: 2025-03-30 12:20:58.371761+00:00. externally triggered: True>
[2025-03-30T12:31:23.493+0000] {logging_mixin.py:190} INFO - Failure caused by API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-30T12:31:23.493+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=aqi_etl_pipeline, task_id=get_aqi_data_Nonthaburi, run_id=manual__2025-03-30T12:20:58.350966+00:00, execution_date=20250330T122058, start_date=20250330T123122, end_date=20250330T123123
[2025-03-30T12:31:23.515+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T12:31:23.520+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 611 for task get_aqi_data_Nonthaburi (API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}; 31509)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 48, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-30T12:31:23.580+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T12:31:23.619+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
