[2025-03-31T01:49:07.696+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T01:49:07.725+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.get_aqi_data_Bangkok scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T01:49:07.736+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.get_aqi_data_Bangkok scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T01:49:07.736+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 4
[2025-03-31T01:49:07.762+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): get_aqi_data_Bangkok> on 2025-03-30 00:00:00+00:00
[2025-03-31T01:49:07.777+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'get_aqi_data_Bangkok', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '700', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmp4oio7cuo']
[2025-03-31T01:49:07.779+0000] {standard_task_runner.py:105} INFO - Job 700: Subtask get_aqi_data_Bangkok
[2025-03-31T01:49:07.794+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=2191) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T01:49:07.795+0000] {standard_task_runner.py:72} INFO - Started process 2210 to run task
[2025-03-31T01:49:07.851+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.get_aqi_data_Bangkok scheduled__2025-03-30T00:00:00+00:00 [running]> on host 34bd8b30e513
[2025-03-31T01:49:07.966+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='get_aqi_data_Bangkok' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T01:49:07.969+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T01:49:07.969+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T01:49:07.970+0000] {logging_mixin.py:190} INFO - Current task name:get_aqi_data_Bangkok state:running start_date:2025-03-31 01:49:07.725706+00:00
[2025-03-31T01:49:07.970+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-31T01:49:07.970+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T01:49:07.971+0000] {logging_mixin.py:190} INFO - Payload being sent: {'city': 'Bangkok', 'country': 'Thailand', 'key': 'your_api_key_here'}
[2025-03-31T01:49:08.269+0000] {logging_mixin.py:190} INFO - Response Status: 403
[2025-03-31T01:49:08.269+0000] {logging_mixin.py:190} INFO - Response Text: {"status":"fail","data":{"message":"Forbidden"}}
[2025-03-31T01:49:08.270+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 52, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 403: {"status":"fail","data":{"message":"Forbidden"}}
[2025-03-31T01:49:08.284+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-31T01:49:08.285+0000] {logging_mixin.py:190} INFO - Task start:2025-03-31 01:49:07.725706+00:00 end:2025-03-31 01:49:08.284063+00:00 duration:0.558357
[2025-03-31T01:49:08.285+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): get_aqi_data_Bangkok> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-30 00:00:00+00:00: scheduled__2025-03-30T00:00:00+00:00, state:running, queued_at: 2025-03-31 01:45:37.384098+00:00. externally triggered: False>
[2025-03-31T01:49:08.285+0000] {logging_mixin.py:190} INFO - Failure caused by API Error 403: {"status":"fail","data":{"message":"Forbidden"}}
[2025-03-31T01:49:08.286+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=aqi_etl_pipeline, task_id=get_aqi_data_Bangkok, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T014907, end_date=20250331T014908
[2025-03-31T01:49:08.306+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T01:49:08.308+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 700 for task get_aqi_data_Bangkok (API Error 403: {"status":"fail","data":{"message":"Forbidden"}}; 2210)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 52, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 403: {"status":"fail","data":{"message":"Forbidden"}}
[2025-03-31T01:49:08.345+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-31T01:49:08.390+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T01:49:08.398+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
