[2025-03-31T02:49:05.027+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T02:49:05.067+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T02:49:05.094+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T02:49:05.095+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-31T02:49:05.144+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): aqi_tasks_group.get_aqi_data_Pathum_Thani> on 2025-03-30 00:00:00+00:00
[2025-03-31T02:49:05.183+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'aqi_tasks_group.get_aqi_data_Pathum_Thani', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '742', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmphsrmegtn']
[2025-03-31T02:49:05.190+0000] {standard_task_runner.py:105} INFO - Job 742: Subtask aqi_tasks_group.get_aqi_data_Pathum_Thani
[2025-03-31T02:49:05.227+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7503) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T02:49:05.230+0000] {standard_task_runner.py:72} INFO - Started process 7506 to run task
[2025-03-31T02:49:05.335+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani scheduled__2025-03-30T00:00:00+00:00 [running]> on host 34bd8b30e513
[2025-03-31T02:49:05.875+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='aqi_tasks_group.get_aqi_data_Pathum_Thani' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T02:49:05.882+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T02:49:05.882+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T02:49:05.884+0000] {logging_mixin.py:190} INFO - Current task name:aqi_tasks_group.get_aqi_data_Pathum_Thani state:running start_date:2025-03-31 02:49:05.067757+00:00
[2025-03-31T02:49:05.887+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-31T02:49:05.887+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T02:49:06.249+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 35, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:49:06.313+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-31T02:49:06.314+0000] {logging_mixin.py:190} INFO - Task start:2025-03-31 02:49:05.067757+00:00 end:2025-03-31 02:49:06.313033+00:00 duration:1.245276
[2025-03-31T02:49:06.314+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): aqi_tasks_group.get_aqi_data_Pathum_Thani> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-30 00:00:00+00:00: scheduled__2025-03-30T00:00:00+00:00, state:running, queued_at: 2025-03-31 01:45:37.384098+00:00. externally triggered: False>
[2025-03-31T02:49:06.314+0000] {logging_mixin.py:190} INFO - Failure caused by API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:49:06.319+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=aqi_etl_pipeline, task_id=aqi_tasks_group.get_aqi_data_Pathum_Thani, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T024905, end_date=20250331T024906
[2025-03-31T02:49:06.368+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T02:49:06.372+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 742 for task aqi_tasks_group.get_aqi_data_Pathum_Thani (API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}; 7506)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 35, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:49:06.414+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-31T02:49:06.440+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T02:49:06.443+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-31T07:19:59.604+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T07:19:59.650+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T07:19:59.669+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani scheduled__2025-03-30T00:00:00+00:00 [queued]>
[2025-03-31T07:19:59.670+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 4
[2025-03-31T07:19:59.737+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): aqi_tasks_group.get_aqi_data_Pathum_Thani> on 2025-03-30 00:00:00+00:00
[2025-03-31T07:19:59.796+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'aqi_tasks_group.get_aqi_data_Pathum_Thani', 'scheduled__2025-03-30T00:00:00+00:00', '--job-id', '922', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpv8113ps1']
[2025-03-31T07:19:59.800+0000] {standard_task_runner.py:105} INFO - Job 922: Subtask aqi_tasks_group.get_aqi_data_Pathum_Thani
[2025-03-31T07:19:59.805+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=1755) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T07:19:59.806+0000] {standard_task_runner.py:72} INFO - Started process 1771 to run task
[2025-03-31T07:20:00.045+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani scheduled__2025-03-30T00:00:00+00:00 [running]> on host 0c0dca5804dc
[2025-03-31T07:20:00.255+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='aqi_tasks_group.get_aqi_data_Pathum_Thani' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-30T00:00:00+00:00'
[2025-03-31T07:20:00.258+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T07:20:00.261+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T07:20:00.263+0000] {logging_mixin.py:190} INFO - Current task name:aqi_tasks_group.get_aqi_data_Pathum_Thani state:running start_date:2025-03-31 07:19:59.651923+00:00
[2025-03-31T07:20:00.264+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-31T07:20:00.265+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T07:20:00.266+0000] {api_etl_pipeline.py:28} INFO - Fetching AQI data with params: {'city': 'Pathum Thani', 'state': 'Pathum Thani', 'country': 'Thailand', 'key': '***'}
[2025-03-31T07:20:00.780+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-31T07:20:00.841+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T07:20:00.842+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=aqi_etl_pipeline, task_id=aqi_tasks_group.get_aqi_data_Pathum_Thani, run_id=scheduled__2025-03-30T00:00:00+00:00, execution_date=20250330T000000, start_date=20250331T071959, end_date=20250331T072000
[2025-03-31T07:20:00.969+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-31T07:20:00.971+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-31T07:20:00.971+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline queued_at:2025-03-31 07:19:53.335868+00:00
[2025-03-31T07:20:00.971+0000] {logging_mixin.py:190} INFO - Task hostname:0c0dca5804dc operator:PythonOperator
[2025-03-31T07:20:01.069+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-31T07:20:01.110+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
