[2025-03-31T02:29:03.571+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T02:29:03.608+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optimized_aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Nonthaburi manual__2025-03-31T02:19:45.757464+00:00 [queued]>
[2025-03-31T02:29:03.619+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optimized_aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Nonthaburi manual__2025-03-31T02:19:45.757464+00:00 [queued]>
[2025-03-31T02:29:03.620+0000] {taskinstance.py:2866} INFO - Starting attempt 4 of 4
[2025-03-31T02:29:03.645+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): aqi_tasks_group.get_aqi_data_Nonthaburi> on 2025-03-31 02:19:45.757464+00:00
[2025-03-31T02:29:03.690+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'optimized_aqi_etl_pipeline', 'aqi_tasks_group.get_aqi_data_Nonthaburi', 'manual__2025-03-31T02:19:45.757464+00:00', '--job-id', '727', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpdd7tmh1l']
[2025-03-31T02:29:03.698+0000] {standard_task_runner.py:105} INFO - Job 727: Subtask aqi_tasks_group.get_aqi_data_Nonthaburi
[2025-03-31T02:29:03.712+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=12298) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T02:29:03.721+0000] {standard_task_runner.py:72} INFO - Started process 12308 to run task
[2025-03-31T02:29:03.932+0000] {task_command.py:467} INFO - Running <TaskInstance: optimized_aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Nonthaburi manual__2025-03-31T02:19:45.757464+00:00 [running]> on host 34bd8b30e513
[2025-03-31T02:29:04.140+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optimized_aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='aqi_tasks_group.get_aqi_data_Nonthaburi' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T02:19:45.757464+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T02:19:45.757464+00:00'
[2025-03-31T02:29:04.141+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T02:29:04.144+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T02:29:04.144+0000] {logging_mixin.py:190} INFO - Current task name:aqi_tasks_group.get_aqi_data_Nonthaburi state:running start_date:2025-03-31 02:29:03.609628+00:00
[2025-03-31T02:29:04.147+0000] {logging_mixin.py:190} INFO - Dag name:optimized_aqi_etl_pipeline and current dag run status:running
[2025-03-31T02:29:04.148+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T02:29:04.509+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 35, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:29:04.538+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-31T02:29:04.539+0000] {logging_mixin.py:190} INFO - Task start:2025-03-31 02:29:03.609628+00:00 end:2025-03-31 02:29:04.538026+00:00 duration:0.928398
[2025-03-31T02:29:04.540+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): aqi_tasks_group.get_aqi_data_Nonthaburi> dag:<DAG: optimized_aqi_etl_pipeline> dagrun:<DagRun optimized_aqi_etl_pipeline @ 2025-03-31 02:19:45.757464+00:00: manual__2025-03-31T02:19:45.757464+00:00, state:running, queued_at: 2025-03-31 02:19:45.770034+00:00. externally triggered: True>
[2025-03-31T02:29:04.540+0000] {logging_mixin.py:190} INFO - Failure caused by API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:29:04.541+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=optimized_aqi_etl_pipeline, task_id=aqi_tasks_group.get_aqi_data_Nonthaburi, run_id=manual__2025-03-31T02:19:45.757464+00:00, execution_date=20250331T021945, start_date=20250331T022903, end_date=20250331T022904
[2025-03-31T02:29:04.565+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T02:29:04.567+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 727 for task aqi_tasks_group.get_aqi_data_Nonthaburi (API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}; 12308)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 35, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:29:04.629+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-31T02:29:04.684+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T02:29:04.698+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
