[2025-03-31T02:26:00.165+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-31T02:26:00.207+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: optimized_aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani manual__2025-03-31T02:19:45.757464+00:00 [queued]>
[2025-03-31T02:26:00.231+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: optimized_aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani manual__2025-03-31T02:19:45.757464+00:00 [queued]>
[2025-03-31T02:26:00.233+0000] {taskinstance.py:2866} INFO - Starting attempt 3 of 4
[2025-03-31T02:26:00.252+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): aqi_tasks_group.get_aqi_data_Pathum_Thani> on 2025-03-31 02:19:45.757464+00:00
[2025-03-31T02:26:00.270+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'optimized_aqi_etl_pipeline', 'aqi_tasks_group.get_aqi_data_Pathum_Thani', 'manual__2025-03-31T02:19:45.757464+00:00', '--job-id', '724', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpuc_e_c8i']
[2025-03-31T02:26:00.275+0000] {standard_task_runner.py:105} INFO - Job 724: Subtask aqi_tasks_group.get_aqi_data_Pathum_Thani
[2025-03-31T02:26:00.282+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=10513) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-31T02:26:00.283+0000] {standard_task_runner.py:72} INFO - Started process 10520 to run task
[2025-03-31T02:26:00.361+0000] {task_command.py:467} INFO - Running <TaskInstance: optimized_aqi_etl_pipeline.aqi_tasks_group.get_aqi_data_Pathum_Thani manual__2025-03-31T02:19:45.757464+00:00 [running]> on host 34bd8b30e513
[2025-03-31T02:26:00.486+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='optimized_aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='aqi_tasks_group.get_aqi_data_Pathum_Thani' AIRFLOW_CTX_EXECUTION_DATE='2025-03-31T02:19:45.757464+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-31T02:19:45.757464+00:00'
[2025-03-31T02:26:00.488+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-31T02:26:00.489+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-31T02:26:00.491+0000] {logging_mixin.py:190} INFO - Current task name:aqi_tasks_group.get_aqi_data_Pathum_Thani state:running start_date:2025-03-31 02:26:00.210820+00:00
[2025-03-31T02:26:00.492+0000] {logging_mixin.py:190} INFO - Dag name:optimized_aqi_etl_pipeline and current dag run status:running
[2025-03-31T02:26:00.494+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-31T02:26:00.850+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 35, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:26:00.896+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-31T02:26:00.897+0000] {logging_mixin.py:190} INFO - Task start:2025-03-31 02:26:00.210820+00:00 end:2025-03-31 02:26:00.895733+00:00 duration:0.684913
[2025-03-31T02:26:00.898+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): aqi_tasks_group.get_aqi_data_Pathum_Thani> dag:<DAG: optimized_aqi_etl_pipeline> dagrun:<DagRun optimized_aqi_etl_pipeline @ 2025-03-31 02:19:45.757464+00:00: manual__2025-03-31T02:19:45.757464+00:00, state:running, queued_at: 2025-03-31 02:19:45.770034+00:00. externally triggered: True>
[2025-03-31T02:26:00.898+0000] {logging_mixin.py:190} INFO - Failure caused by API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:26:00.899+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=optimized_aqi_etl_pipeline, task_id=aqi_tasks_group.get_aqi_data_Pathum_Thani, run_id=manual__2025-03-31T02:19:45.757464+00:00, execution_date=20250331T021945, start_date=20250331T022600, end_date=20250331T022600
[2025-03-31T02:26:00.944+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-31T02:26:00.944+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 724 for task aqi_tasks_group.get_aqi_data_Pathum_Thani (API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}; 10520)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 35, in _get_aqi_data
    raise ValueError(f"API Error {response.status_code}: {response.text}")
ValueError: API Error 400: {"status":"fail","data":{"message":"arguments_missing"}}
[2025-03-31T02:26:01.001+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-31T02:26:01.038+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-31T02:26:01.043+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
