[2025-03-30T07:17:30.159+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-30T07:17:30.417+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: aqi_etl_pipeline.load_aqi_to_postgres_Bang_Na manual__2025-03-30T07:17:16.418341+00:00 [queued]>
[2025-03-30T07:17:30.555+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: aqi_etl_pipeline.load_aqi_to_postgres_Bang_Na manual__2025-03-30T07:17:16.418341+00:00 [queued]>
[2025-03-30T07:17:30.571+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-03-30T07:17:30.811+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): load_aqi_to_postgres_Bang_Na> on 2025-03-30 07:17:16.418341+00:00
[2025-03-30T07:17:31.003+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'aqi_etl_pipeline', 'load_aqi_to_postgres_Bang_Na', 'manual__2025-03-30T07:17:16.418341+00:00', '--job-id', '349', '--raw', '--subdir', 'DAGS_FOLDER/api_etl_pipeline.py', '--cfg-path', '/tmp/tmpld904cwk']
[2025-03-30T07:17:31.030+0000] {standard_task_runner.py:105} INFO - Job 349: Subtask load_aqi_to_postgres_Bang_Na
[2025-03-30T07:17:31.079+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=7931) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-03-30T07:17:31.088+0000] {standard_task_runner.py:72} INFO - Started process 8028 to run task
[2025-03-30T07:17:31.730+0000] {task_command.py:467} INFO - Running <TaskInstance: aqi_etl_pipeline.load_aqi_to_postgres_Bang_Na manual__2025-03-30T07:17:16.418341+00:00 [running]> on host 58b9640d9ecf
[2025-03-30T07:17:33.451+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='aqi_etl_pipeline' AIRFLOW_CTX_TASK_ID='load_aqi_to_postgres_Bang_Na' AIRFLOW_CTX_EXECUTION_DATE='2025-03-30T07:17:16.418341+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-30T07:17:16.418341+00:00'
[2025-03-30T07:17:33.453+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-30T07:17:33.477+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-30T07:17:33.478+0000] {logging_mixin.py:190} INFO - Current task name:load_aqi_to_postgres_Bang_Na state:running start_date:2025-03-30 07:17:30.429588+00:00
[2025-03-30T07:17:33.481+0000] {logging_mixin.py:190} INFO - Dag name:aqi_etl_pipeline and current dag run status:running
[2025-03-30T07:17:33.485+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-03-30T07:17:33.582+0000] {base.py:84} INFO - Retrieving connection '***_default'
[2025-03-30T07:17:33.626+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 87, in _load_aqi_to_postgres
    aqi_value = data["data"]["current"]["pollution"]["aqius"]
                ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'current'
[2025-03-30T07:17:33.696+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-30T07:17:33.701+0000] {logging_mixin.py:190} INFO - Task start:2025-03-30 07:17:30.429588+00:00 end:2025-03-30 07:17:33.695951+00:00 duration:3.266363
[2025-03-30T07:17:33.709+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): load_aqi_to_***_Bang_Na> dag:<DAG: aqi_etl_pipeline> dagrun:<DagRun aqi_etl_pipeline @ 2025-03-30 07:17:16.418341+00:00: manual__2025-03-30T07:17:16.418341+00:00, state:running, queued_at: 2025-03-30 07:17:16.429489+00:00. externally triggered: True>
[2025-03-30T07:17:33.710+0000] {logging_mixin.py:190} INFO - Failure caused by 'current'
[2025-03-30T07:17:33.713+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=aqi_etl_pipeline, task_id=load_aqi_to_***_Bang_Na, run_id=manual__2025-03-30T07:17:16.418341+00:00, execution_date=20250330T071716, start_date=20250330T071730, end_date=20250330T071733
[2025-03-30T07:17:34.047+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-03-30T07:17:34.047+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 349 for task load_aqi_to_***_Bang_Na ('current'; 8028)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/api_etl_pipeline.py", line 87, in _load_aqi_to_postgres
    aqi_value = data["data"]["current"]["pollution"]["aqius"]
                ~~~~~~~~~~~~^^^^^^^^^^^
KeyError: 'current'
[2025-03-30T07:17:34.189+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-30T07:17:34.315+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-30T07:17:34.325+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
